networks:
  default:
    driver_opts:
      com.docker.network.bridge.gateway_mode_ipv4: isolated
      com.docker.network.bridge.gateway_mode_ipv6: isolated
    internal: true
    ipam:
      config:
      - subnet: ${SAMPLE_METADATA_SANDBOX_SUBNET_0}
services:
  default:
    build:
      context: .
      dockerfile: Dockerfile
    dns:
    - ${SAMPLE_METADATA_SANDBOX_DNS_0}
    image: ct-covert-ops:latest
    init: true
